services:
  - type: web
    name: ai-notatnik-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HF_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
